'''Contain template details for creating a python library'''
lib_header  = '''"""
Generated by SGWrapperGen - DO NOT EDIT!

SwinGame wrapper for Python using ctypes module

Links to platform SGSDK library (SGSDK.dll, libSGSDK.so, or libSGSDK.dylib)

"""
'''

# './c_lib/lib_import_header.txt')
_lib_import_header= '''#include "%(name)s.h"'''
    
#TODO: Add module level description to module header __doc__ block
header = '''"""MODULE DESCRIPTION HERE!
"""

# Generated by SGWrapperGen - DO NOT EDIT!
# SwinGame wrapper for Python - %(name)s
# Wrapping %(pascal_name)s.pas

'''

# import sgsdk # dll bindings (methods/functions)
# import types # known types (structs, enums)

method = """
def %(uname)s(%(params)s):
    '''%(doc)s
    params: %(params)s
    '''
    %(calls.name)s(%(calls.args)s)

"""
#void %(uname)s(%(params)s)
#{
#    %(calls.name)s(%(calls.args)s);
#}


function = """
def %(uname)s(%(params)s):
    '''%(doc)s
    params: %(params)s
    returns: %(return_type)s
    '''
    return %(the_call)s

"""
#%(return_type)s(%(params)s)
#{
#    return %(the_call)s;
#}


